/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;

import controlador.Controlador;
import entidades.Cliente;
import entidades.Regimenes;
import entidades.Terceros;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import utils.Validator;

/**
 *
 * @author Osmar
 */
public class añadirTercero extends javax.swing.JDialog {

    private ArrayList<Object> listaClientesD;
    private ArrayList<Object> listaClientesA;
    private ArrayList<Object> listaRegimenesA;
    private ArrayList<Object> listaRegimenesD;
    private ArrayList<Object> allClientes;
    private ArrayList<Object> allRegimenes;
    private DefaultListModel<String> modeloClientesA;
    private DefaultListModel<String> modeloClientesD;
    private DefaultListModel<String> modeloRegimenesA;
    private DefaultListModel<String> modeloRegimenesD;
    private Clickeo regimenes,clientes;
    private static Controlador c;
    
    
    public añadirTercero(java.awt.Frame parent, boolean modal, Controlador controler) {
        super(parent, modal);
        initComponents();
        
        c = controler;
        
        // Inicializamos las listas que vamos a usar para despues añadir
        listaClientesD = new ArrayList<>();
        listaClientesA = new ArrayList<>();
        listaRegimenesA = new ArrayList<>();
        listaRegimenesD = new ArrayList<>();
        allClientes = new ArrayList<>();
        allRegimenes = new ArrayList<>();
        
        //Inicializamos los modelos de la lista
        modeloClientesA = new DefaultListModel<>();
        modeloClientesD = new DefaultListModel<>();
        modeloRegimenesA = new DefaultListModel<>();
        modeloRegimenesD = new DefaultListModel<>();
        
        //asiganamos los modelos a sus respectivas listas
        listaA.setModel(modeloRegimenesA);
        ListaD.setModel(modeloRegimenesD);
        listaCA.setModel(modeloClientesA);
        ListaCD.setModel(modeloClientesD);
        
        //Declaramos las variables de tipo clickeo
        clientes = new Clickeo(modeloClientesA, modeloClientesD, listaClientesA, listaClientesD, allClientes, listaCA, ListaCD);
        regimenes = new Clickeo(modeloRegimenesA, modeloRegimenesD, listaRegimenesA, listaRegimenesD, allRegimenes, listaA, ListaD);
        
        //Añadimos las variables clickeo a su respectivas listas
        
        listaA.addMouseListener(regimenes);
        ListaD.addMouseListener(regimenes);
        listaCA.addMouseListener(clientes);
        ListaCD.addMouseListener(clientes);
        
        cargarClientesYRegimenes();

        // FlatLaf styling
        TNom.putClientProperty("JTextField.roundRect", true);
        TNom.putClientProperty("JTextField.placeholderText", "Nombre completo...");
        TRfc.putClientProperty("JTextField.roundRect", true);
        TRfc.putClientProperty("JTextField.placeholderText", "RFC de 12 o 13 dígitos...");
        TCp.putClientProperty("JTextField.roundRect", true);
        TCp.putClientProperty("JTextField.placeholderText", "Código Postal...");
        TCorr.putClientProperty("JTextField.roundRect", true);
        TCorr.putClientProperty("JTextField.placeholderText", "Correo electrónico...");

        jButton1.putClientProperty("JButton.buttonType", "roundRect");

        setResizable(false);
        setJMenuBar(null);
        setLocationRelativeTo(parent);
    }
    
    private void cargarClientesYRegimenes(){
        modeloRegimenesD.removeAllElements();
        modeloClientesD.removeAllElements();
        
        for(Regimenes o : c.getRegimenes()){
            allRegimenes.add(o);
            modeloRegimenesD.addElement(o.regimen);
        }
        
        for(Cliente cli : c.getAllClientes().values()){
            allClientes.add(cli);
            modeloClientesD.addElement(cli.nombre);
        }
        
        
    }
    
    private void borrarValores(){
        TNom.setText("");
        TRfc.setText("");
        TCp.setText("");
        TCorr.setText("");
        listaClientesA.clear();
        listaClientesD.clear();
        listaRegimenesA.clear();
        listaRegimenesD.clear();
        allClientes.clear();
        allRegimenes.clear();
        
        cargarClientesYRegimenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TCorr = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TNom = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaA = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        TRfc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TCp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaCD = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaCA = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        ListaD = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 380));

        TCorr.setMaximumSize(new java.awt.Dimension(7, 22));

        jLabel7.setText("Datos Terceros");

        jLabel1.setText("Nombre");

        TNom.setMaximumSize(new java.awt.Dimension(7, 22));

        listaA.setMaximumSize(null);
        listaA.setMinimumSize(new java.awt.Dimension(350, 90));
        listaA.setPreferredSize(new java.awt.Dimension(350, 90));
        jScrollPane1.setViewportView(listaA);

        jLabel2.setText("RFC");

        TRfc.setMaximumSize(new java.awt.Dimension(7, 22));

        jLabel8.setText("Regimene(s)");

        jLabel3.setText("C.P.");

        jLabel9.setText("Regimenes Disponibles");

        TCp.setMaximumSize(new java.awt.Dimension(7, 22));

        jLabel4.setText("Correo");

        jLabel10.setText("Cliente(s)");

        jLabel11.setText("Clientes Disponibles");

        ListaCD.setToolTipText("");
        ListaCD.setMaximumSize(null);
        ListaCD.setMinimumSize(new java.awt.Dimension(350, 90));
        ListaCD.setPreferredSize(new java.awt.Dimension(270, 89));
        jScrollPane3.setViewportView(ListaCD);

        listaCA.setMaximumSize(null);
        listaCA.setMinimumSize(new java.awt.Dimension(350, 90));
        listaCA.setPreferredSize(new java.awt.Dimension(270, 89));
        jScrollPane4.setViewportView(listaCA);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(ListaD);

        jMenu1.setText("Inicio");

        jMenuItem10.setText("Incio");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Terceros");

        jMenuItem5.setText("Buscar");
        jMenu2.add(jMenuItem5);

        jMenuItem8.setText("Eliminar");
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("EFirmas");

        jMenuItem11.setText("Editar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Listas");

        jMenuItem12.setText("Ver listas");
        jMenu4.add(jMenuItem12);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TNom, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TCorr, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TCp, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TNom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TCp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TCorr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(TNom.getText().isEmpty() || TCp.getText().isEmpty() ||
            TRfc.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Valores no validos");
            return;
        }

        if(TNom.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Nombre no valido");
            return;
        }

        if(!Validator.validarCorreo(TCorr.getText()) && !TCorr.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Correo no valido");
            return;
        }

        if(!Validator.validarCodigoPostal(TCp.getText())){
            JOptionPane.showMessageDialog(rootPane, "Codigo Postal no valido");
            return;
        }

        if(!Validator.validarRFC(TRfc.getText())){
            JOptionPane.showMessageDialog(rootPane, "RFC no valido");
            return;
        }

        ArrayList<Integer> idReg = new ArrayList<>();
        ArrayList<Integer> idClientes = new ArrayList<>();

        for(Object regimen : listaRegimenesA) idReg.add(((Regimenes)regimen).getId());

        for(Object cliente : listaClientesA) idClientes.add(((Cliente)cliente).id_persona);
        
        Terceros tercero = new Terceros(
            TNom.getText(),
            TRfc.getText(),
            TCp.getText(),
            TCorr.getText());

        tercero.idsRegimenes = idReg;

        String respuesta = c.insertTercero(tercero, idClientes);

        if(!"correcto".equals(respuesta)) {
            JOptionPane.showMessageDialog(rootPane, respuesta);
            return;
        }

        borrarValores();
        JOptionPane.showMessageDialog(rootPane, "Tercero insertado con exito");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(añadirTercero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(añadirTercero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(añadirTercero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(añadirTercero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                añadirTercero dialog = new añadirTercero(new javax.swing.JFrame(), true, c);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaCD;
    private javax.swing.JList<String> ListaD;
    private javax.swing.JTextField TCorr;
    private javax.swing.JTextField TCp;
    private javax.swing.JTextField TNom;
    private javax.swing.JTextField TRfc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> listaA;
    private javax.swing.JList<String> listaCA;
    // End of variables declaration//GEN-END:variables
}
