package UI;

import controlador.Controlador;
import entidades.Cliente;
import entidades.Regimenes;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Osmar
 */
public class CambiarRegimenes extends javax.swing.JDialog {

    private static Controlador c;
    private static Cliente cliente;
    private DefaultListModel<String> modeloActuales;
    private DefaultListModel<String> modeloDisponibles;
    private ArrayList<Regimenes> añadidos;
    private ArrayList<Regimenes> quitados;
    private ArrayList<Regimenes> all;
    private boolean hayCambios;
    
    public CambiarRegimenes(java.awt.Frame parent, boolean modal,Controlador controler, Cliente client) {
        super(parent, modal);
        initComponents();
        c = controler;
        cliente = client;
        modeloActuales = new DefaultListModel();
        modeloDisponibles = new DefaultListModel();
        all = c.getRegimenes();
        
        listaA.setModel(modeloActuales);
        ListaD.setModel(modeloDisponibles);
        
        añadidos = new ArrayList<>();
        quitados = new ArrayList<>();
        
        hayCambios = false;
        
        setRegimenes();
    }

    private void setRegimenes(){
        
        for(Regimenes r : all){
            if(cliente.idsRegimenes.contains(r.getId())){
                modeloActuales.addElement(r.regimen);
            }
            else{
                modeloDisponibles.addElement(r.regimen);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaA = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaD = new javax.swing.JList<>();
        quitarR = new javax.swing.JButton();
        añadirR = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        listaA.setMaximumSize(new java.awt.Dimension(237, 89));
        listaA.setMinimumSize(new java.awt.Dimension(237, 89));
        jScrollPane1.setViewportView(listaA);

        jLabel1.setText("Regimenes Actuales");

        jLabel2.setText("Regimenes Disponibles");

        ListaD.setMaximumSize(new java.awt.Dimension(237, 89));
        ListaD.setMinimumSize(new java.awt.Dimension(237, 89));
        jScrollPane2.setViewportView(ListaD);

        quitarR.setText(">>>");
        quitarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarRActionPerformed(evt);
            }
        });

        añadirR.setText("<<<");
        añadirR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirRActionPerformed(evt);
            }
        });

        jButton3.setText("Guardar Cambios");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu1.setText("Inicio");

        jMenuItem10.setText("Incio");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Terceros");

        jMenuItem5.setText("Buscar");
        jMenu2.add(jMenuItem5);

        jMenuItem7.setText("Agregar");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Eliminar");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Editar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("EFirmas");

        jMenuItem11.setText("Editar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Listas");

        jMenuItem12.setText("Ver listas");
        jMenu4.add(jMenuItem12);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(quitarR, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(añadirR, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitarR)
                    .addComponent(añadirR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        Index i = new Index(c);
        this.setVisible(false);
        i.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void quitarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarRActionPerformed
        String nombre = listaA.getSelectedValue();
        
        if(nombre == null) {
            
            JOptionPane.showMessageDialog(rootPane, "Selecciona un regimen");
            return;
            
        }
        
        Regimenes r = null;
        
        for(Regimenes re : all){
            if(re.regimen.equals(nombre)){
                r = re;
                break;
            }
        }
        modeloActuales.removeElement(nombre);
        quitados.add(r);
        modeloDisponibles.addElement(r.regimen);
        if(!hayCambios) hayCambios = true;
    }//GEN-LAST:event_quitarRActionPerformed

    private void añadirRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirRActionPerformed
        Regimenes r = null;
        String nombre = ListaD.getSelectedValue();
        
        if(nombre == null) {
            
            JOptionPane.showMessageDialog(rootPane, "Selecciona un regimen");
            return;
            
        }
        
        for(Regimenes re : all){
            if(re.regimen.equals(nombre)){
                r = re;
                break;
            }
        }
        
        modeloDisponibles.removeElement(nombre);
        añadidos.add(r);
        modeloActuales.addElement(r.regimen);
        if(!hayCambios) hayCambios = true;
    }//GEN-LAST:event_añadirRActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        for(Regimenes r : añadidos){
            String s = c.addRegimenACliente(cliente.id_persona, r.getId());
            if(s.equals("correcto")) continue;
            else{
                JOptionPane.showMessageDialog(rootPane, s);
                return;
            }
        }
        
        for(Regimenes r : quitados){
            String s = c.deleteRegimenACliente(cliente.id_persona, r.getId());
            if(s.equals("correcto")) continue;
            else{
                JOptionPane.showMessageDialog(rootPane, s);
                return;
            }
        }
        
        JOptionPane.showMessageDialog(rootPane, "Cambios exitosos");
        hayCambios = false;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(hayCambios){
            int respuesta = JOptionPane.showConfirmDialog(rootPane, "Hay cambios, esta seguro de salir??");
            if(JOptionPane.YES_OPTION == respuesta){
                this.dispose();
            }
            return;
        }
        
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarRegimenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarRegimenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarRegimenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarRegimenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CambiarRegimenes dialog = new CambiarRegimenes(new javax.swing.JFrame(), true,c,cliente);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaD;
    private javax.swing.JButton añadirR;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String
    > listaA;
    private javax.swing.JButton quitarR;
    // End of variables declaration//GEN-END:variables
}
