/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;

import controlador.Controlador;
import entidades.Cliente;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Osmar
 */
public class DetallesClientes extends javax.swing.JDialog {

    private static Controlador c;
    private static Cliente cliente;
    private static final String REGEX_EMAIL = "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
    private static final String REGEX_CP = "^[0-9]{5}$";
    
    public DetallesClientes(java.awt.Frame parent, boolean modal, Controlador controler, Cliente i) {
        super(parent, modal);
        initComponents();
        c = controler;
        cliente = i;
        setContadores();
        setValues();
    }
    
    private void setContadores(){
        ComboContadores.removeAllItems();
        
        for(Integer i : c.getAllContadores().keySet()){
            ComboContadores.addItem(""+ i);
        }
                
    }
    
    private void setValues(){
        FNombre.setText(cliente.nombre);
        FRFC.setText(cliente.rfc);
        FCP.setText(cliente.cp);
        FCorreo.setText(cliente.correo);
        FHonorarios.setText(""+cliente.honorarios);
        ComboContadores.setSelectedItem((Integer) cliente.id_contador );
    }
    
    private void setUnEditable(){
        FNombre.setEditable(false);
        FRFC.setEditable(false);
        FCP.setEditable(false);
        FCorreo.setEditable(false);
        FHonorarios.setEditable(false);
        checkCP.setSelected(false);
        checkContador.setSelected(false);
        checkCorreo.setSelected(false);
        checkHonorarios.setSelected(false);
        checkNombre.setSelected(false);
    }
    
    private boolean verificarCorreo(String correo){
        return Pattern.matches(REGEX_EMAIL, correo);
    }
    
    private boolean verificarCP(String cp){
        return Pattern.matches(REGEX_CP, cp);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        FRFC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FCP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FHonorarios = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ComboContadores = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        checkNombre = new javax.swing.JCheckBox();
        checkCP = new javax.swing.JCheckBox();
        checkCorreo = new javax.swing.JCheckBox();
        checkHonorarios = new javax.swing.JCheckBox();
        checkContador = new javax.swing.JCheckBox();
        cambiar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        FNombre.setEditable(false);
        FNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNombreActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        FRFC.setEditable(false);

        jLabel2.setText("RFC");

        FCP.setEditable(false);
        FCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCPActionPerformed(evt);
            }
        });

        jLabel3.setText("C.P.");

        FCorreo.setEditable(false);

        jLabel4.setText("Correo.");

        FHonorarios.setEditable(false);

        jLabel5.setText("Honorarios");

        jLabel6.setText("Id Contador");

        ComboContadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboContadores.setEnabled(false);
        ComboContadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboContadoresActionPerformed(evt);
            }
        });

        jLabel7.setText("Editable");

        checkNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNombreActionPerformed(evt);
            }
        });

        checkCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCPActionPerformed(evt);
            }
        });

        checkCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCorreoActionPerformed(evt);
            }
        });

        checkHonorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkHonorariosActionPerformed(evt);
            }
        });

        checkContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkContadorActionPerformed(evt);
            }
        });

        cambiar.setText("Cambiar");
        cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarActionPerformed(evt);
            }
        });

        jMenu1.setText("Inicio");

        jMenuItem10.setText("Incio");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Terceros");

        jMenuItem5.setText("Buscar");
        jMenu2.add(jMenuItem5);

        jMenuItem7.setText("Agregar");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Eliminar");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Editar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("EFirmas");

        jMenuItem11.setText("Editar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Listas");

        jMenuItem12.setText("Ver listas");
        jMenu4.add(jMenuItem12);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FCP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FRFC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(FHonorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ComboContadores, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkNombre)
                            .addComponent(checkCP)
                            .addComponent(checkCorreo)
                            .addComponent(checkHonorarios)
                            .addComponent(checkContador))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(checkNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(checkCP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FHonorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(checkHonorarios))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(ComboContadores, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(checkContador)))
                    .addComponent(checkCorreo))
                .addGap(9, 9, 9)
                .addComponent(cambiar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        Index i = new Index(c);
        this.setVisible(false);
        i.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void FNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNombreActionPerformed

    private void FCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FCPActionPerformed

    private void checkNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNombreActionPerformed
        if(FNombre.isEditable()) FNombre.setEditable(false);
        else FNombre.setEditable(true);
    }//GEN-LAST:event_checkNombreActionPerformed

    private void checkCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCPActionPerformed
       if(FCP.isEditable()) FCP.setEditable(false);
       else FCP.setEditable(true);
    }//GEN-LAST:event_checkCPActionPerformed

    private void checkCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCorreoActionPerformed
        if(FCorreo.isEditable()) FCorreo.setEditable(false);
        else FCorreo.setEditable(true);
    }//GEN-LAST:event_checkCorreoActionPerformed

    private void checkHonorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkHonorariosActionPerformed
        if(FHonorarios.isEditable()) FHonorarios.setEditable(false);
        else FHonorarios.setEditable(true);
    }//GEN-LAST:event_checkHonorariosActionPerformed

    private void ComboContadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboContadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboContadoresActionPerformed

    private void checkContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkContadorActionPerformed
        if(ComboContadores.isEnabled()) ComboContadores.setEnabled(false);
        else ComboContadores.setEnabled(true);
    }//GEN-LAST:event_checkContadorActionPerformed

    private void cambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarActionPerformed
        if(FCP.getText().isEmpty() || FCorreo.getText().isEmpty() || FNombre.getText().isEmpty() 
                || FHonorarios.getText().isEmpty() || ComboContadores.getSelectedIndex() == 1){
            
            JOptionPane.showMessageDialog(this, "Ningun campo puede estar vacio");
            return;
            
        }
        
        if(!verificarCP(FCP.getText())){
            
            JOptionPane.showMessageDialog(this, "Codigo Postal no valido");
            return;
        }
            

        if(!verificarCorreo(FCorreo.getText())){
            
            JOptionPane.showMessageDialog(this, "Correo no valido");
            return;
        
        }
        
        int honorarios;
        
        try{
            
            honorarios = Integer.parseInt(FHonorarios.getText());
            
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Los honorarios tienen que ser un numero valido");
            return;
        }
        
        int decision = JOptionPane.showConfirmDialog(this, "Estas seguro de cambiar los datos");
        
        if(JOptionPane.YES_OPTION == decision){
            
            cliente.updateCliente(
                    FNombre.getText(), 
                       FCP.getText(), 
                    FCorreo.getText(),
                          honorarios, 
                          Integer.parseInt((String)ComboContadores.getSelectedItem())
            );
            
            String respuesta = c.updateCliente(cliente);
            
            JOptionPane.showMessageDialog(this, respuesta);
        }
        
        setValues();
        setUnEditable();
    }//GEN-LAST:event_cambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetallesClientes dialog = new DetallesClientes(new javax.swing.JFrame(), true, c, cliente);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboContadores;
    private javax.swing.JTextField FCP;
    private javax.swing.JTextField FCorreo;
    private javax.swing.JTextField FHonorarios;
    private javax.swing.JTextField FNombre;
    private javax.swing.JTextField FRFC;
    private javax.swing.JButton cambiar;
    private javax.swing.JCheckBox checkCP;
    private javax.swing.JCheckBox checkContador;
    private javax.swing.JCheckBox checkCorreo;
    private javax.swing.JCheckBox checkHonorarios;
    private javax.swing.JCheckBox checkNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables


}
