/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;

import controlador.Controlador;
import entidades.Cliente;
import entidades.Contadores;
import entidades.Regimenes;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import utils.Validator;

/**
 *
 * @author Osmar
 */
public class DetallesClientes extends javax.swing.JDialog {

    private static Controlador c;
    private static Cliente cliente;
    private boolean hayCambios;
    private ArrayList<Contadores> contadores;
    private DefaultListModel listaR;
    
    public DetallesClientes(java.awt.Frame parent, boolean modal, Controlador controler, Cliente i) {
        super(parent, modal);
        initComponents();
        
        c = controler;
        cliente = i;
        contadores = new ArrayList<>();
        listaR = new DefaultListModel();
        
        listaRegimenes.setModel(listaR);
        
        setContadores();
        setValues();
        
        // FlatLaf styling
        FNombre.putClientProperty("JTextField.roundRect", true);
        FCP.putClientProperty("JTextField.roundRect", true);
        FRFC.putClientProperty("JTextField.roundRect", true);
        FCorreo.putClientProperty("JTextField.roundRect", true);
        FHonorarios.putClientProperty("JTextField.roundRect", true);

        ComboContadores.putClientProperty("JComboBox.isButtonRoundRect", true);

        VerTerceros.putClientProperty("JButton.buttonType", "roundRect");
        cambiar.putClientProperty("JButton.buttonType", "roundRect");
        cambiar1.putClientProperty("JButton.buttonType", "roundRect");
        regimenes.putClientProperty("JButton.buttonType", "roundRect");

        hayCambios = false;

        setResizable(false);
        setJMenuBar(null);
        setLocationRelativeTo(parent);
    }
    
    private void setContadores(){
        ComboContadores.removeAllItems();
        ComboContadores.addItem("Selecciona un contador");
        for(Contadores i : c.getAllContadores().values()){
            ComboContadores.addItem(i.nombre);
            contadores.add(i);
        }
                
    }
    
    private void setValues(){
        FNombre.setText(cliente.nombre);
        FRFC.setText(cliente.rfc);
        FCP.setText(cliente.cp);
        FCorreo.setText(cliente.correo);
        FHonorarios.setText(""+cliente.honorarios);
        
        
        ArrayList<Regimenes> regimens = c.getRegimenes();
        
        for(Regimenes r : regimens){
            
            if(cliente.idsRegimenes.contains(r.getId())){
                listaR.addElement(r.regimen);
            }
        }
        
        if (cliente.id_contador > 0 && c.getAllContadores().containsKey(cliente.id_contador)) {
            ComboContadores.setSelectedItem(c.getAllContadores().get(cliente.id_contador).nombre);
        } else {
            ComboContadores.setSelectedIndex(0);
        }
    }
    
    private void setUnEditable(){
        FNombre.setEditable(false);
        FRFC.setEditable(false);
        FCP.setEditable(false);
        FCorreo.setEditable(false);
        FHonorarios.setEditable(false);
        checkCP.setSelected(false);
        checkContador.setSelected(false);
        checkCorreo.setSelected(false);
        checkHonorarios.setSelected(false);
        checkNombre.setSelected(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cambiar1 = new javax.swing.JButton();
        FNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        FRFC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FCP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FHonorarios = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ComboContadores = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        checkNombre = new javax.swing.JCheckBox();
        checkCP = new javax.swing.JCheckBox();
        checkCorreo = new javax.swing.JCheckBox();
        checkHonorarios = new javax.swing.JCheckBox();
        checkContador = new javax.swing.JCheckBox();
        cambiar = new javax.swing.JButton();
        regimenes = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaRegimenes = new javax.swing.JList<>();
        VerTerceros = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();

        cambiar1.setText("Editar E-Firma");
        cambiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiar1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        FNombre.setEditable(false);
        FNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNombreActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        FRFC.setEditable(false);

        jLabel2.setText("RFC");

        FCP.setEditable(false);
        FCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCPActionPerformed(evt);
            }
        });

        jLabel3.setText("C.P.");

        FCorreo.setEditable(false);

        jLabel4.setText("Correo.");

        FHonorarios.setEditable(false);

        jLabel5.setText("Honorarios");

        jLabel6.setText("Id Contador");

        ComboContadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboContadores.setEnabled(false);
        ComboContadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboContadoresActionPerformed(evt);
            }
        });

        jLabel7.setText("Editable");

        checkNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNombreActionPerformed(evt);
            }
        });

        checkCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCPActionPerformed(evt);
            }
        });

        checkCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCorreoActionPerformed(evt);
            }
        });

        checkHonorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkHonorariosActionPerformed(evt);
            }
        });

        checkContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkContadorActionPerformed(evt);
            }
        });

        cambiar.setText("Cambiar");
        cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarActionPerformed(evt);
            }
        });

        regimenes.setText("cambiar regimenes");
        regimenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regimenesActionPerformed(evt);
            }
        });

        jLabel8.setText("Regimenes");

        jScrollPane1.setViewportView(listaRegimenes);

        VerTerceros.setText("Ver Terceros");
        VerTerceros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerTercerosActionPerformed(evt);
            }
        });

        jMenu1.setText("Inicio");

        jMenuItem10.setText("Incio");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Terceros");

        jMenuItem5.setText("Buscar");
        jMenu2.add(jMenuItem5);

        jMenuItem7.setText("Agregar");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Eliminar");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Editar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("EFirmas");

        jMenuItem11.setText("Editar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Listas");

        jMenuItem12.setText("Ver listas");
        jMenu4.add(jMenuItem12);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(regimenes))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(FCP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(FRFC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(FNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(FHonorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(ComboContadores, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkNombre)
                                            .addComponent(checkCP)
                                            .addComponent(checkCorreo)
                                            .addComponent(checkHonorarios)
                                            .addComponent(checkContador))))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VerTerceros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(checkNombre)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(checkCP))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(FHonorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addComponent(checkHonorarios))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(ComboContadores, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(checkContador)))
                            .addComponent(checkCorreo))
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cambiar)
                    .addComponent(regimenes)
                    .addComponent(VerTerceros))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void FNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNombreActionPerformed

    private void FCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FCPActionPerformed

    private void checkNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNombreActionPerformed
        if(FNombre.isEditable()) {
            FNombre.setEditable(false);
            
        }
        else {
            FNombre.setEditable(true);
            if(!hayCambios) hayCambios = true;
        }
    }//GEN-LAST:event_checkNombreActionPerformed

    private void checkCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCPActionPerformed
       if(FCP.isEditable()) {
           FCP.setEditable(false);
           
       }
       else {
           FCP.setEditable(true);
           if(!hayCambios) hayCambios = true;
       }
       
    }//GEN-LAST:event_checkCPActionPerformed

    private void checkCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCorreoActionPerformed
        if(FCorreo.isEditable()) {
            FCorreo.setEditable(false);
            
        }
        else {
            if(!hayCambios) hayCambios = true;
            FCorreo.setEditable(true);
        }
    }//GEN-LAST:event_checkCorreoActionPerformed

    private void checkHonorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkHonorariosActionPerformed
        if(FHonorarios.isEditable()) {
            FHonorarios.setEditable(false);
            
        }
        else {
            if(!hayCambios) hayCambios = true;
            FHonorarios.setEditable(true);
        }
    }//GEN-LAST:event_checkHonorariosActionPerformed

    private void ComboContadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboContadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboContadoresActionPerformed

    private void checkContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkContadorActionPerformed
        if(ComboContadores.isEnabled()) {
            ComboContadores.setEnabled(false);
            
        }
        else {
            if(!hayCambios) hayCambios = true;
            ComboContadores.setEnabled(true);
        }
    }//GEN-LAST:event_checkContadorActionPerformed

    private void cambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarActionPerformed
        if(FCP.getText().isEmpty() || FCorreo.getText().isEmpty() || FNombre.getText().isEmpty() 
                || FHonorarios.getText().isEmpty() || ComboContadores.getSelectedIndex() == 0){
            
            JOptionPane.showMessageDialog(this, "Ningun campo puede estar vacio");
            return;
            
        }
        
        if(!Validator.validarCodigoPostal(FCP.getText())){
            
            JOptionPane.showMessageDialog(this, "Codigo Postal no valido");
            return;
        }
            

        if(!Validator.validarCorreo(FCorreo.getText())){
            
            JOptionPane.showMessageDialog(this, "Correo no valido");
            return;
        
        }
        
        int honorarios;
        
        try{
            
            honorarios = Integer.parseInt(FHonorarios.getText());
            
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Los honorarios tienen que ser un numero valido");
            return;
        }
        
        int idContador = 0;
        
        for(Contadores co : contadores){
            
            if(co.nombre.equals(ComboContadores.getSelectedItem())) {
                idContador = co.getId();
                break;
            }
        }
        
        if(idContador == 0){
            JOptionPane.showMessageDialog(rootPane, "Selecciona un contador");
            return;
        }
        
        int decision = JOptionPane.showConfirmDialog(this, "Estas seguro de cambiar los datos");
        
        if(JOptionPane.YES_OPTION == decision){
            
            cliente.updateCliente(
                    FNombre.getText(), 
                       FCP.getText(), 
                    FCorreo.getText(),
                    honorarios, 
                idContador
            );
            
            String respuesta = c.updateCliente(cliente);
            
            JOptionPane.showMessageDialog(this, respuesta);
        }
        
        setValues();
        setUnEditable();
        hayCambios = false;
    }//GEN-LAST:event_cambiarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int opcion;
        
        if(hayCambios) {
            
            opcion = JOptionPane.showConfirmDialog(rootPane, "Hay cambios pendientes deseas cerrar??");
            if(JOptionPane.YES_OPTION == opcion) this.dispose();
            
            return;
        }
        
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void cambiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiar1ActionPerformed
        new EditarFirmaDialog((java.awt.Window) this.getOwner(), c, cliente).setVisible(true);
    }//GEN-LAST:event_cambiar1ActionPerformed

    private void regimenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regimenesActionPerformed
        CambiarRegimenes cr = new CambiarRegimenes((java.awt.Frame) this.getOwner(), rootPaneCheckingEnabled, c, cliente,"clientes");
        cr.setVisible(true);
        
        // Refresh regimes list in details view
        listaR.clear();
        ArrayList<Regimenes> regimens = c.getRegimenes();
        for(Regimenes r : regimens){
            if(cliente.idsRegimenes.contains(r.getId())){
                listaR.addElement(r.regimen);
            }
        }
    }//GEN-LAST:event_regimenesActionPerformed

    private void VerTercerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerTercerosActionPerformed
        BuscarPersonas bp = new BuscarPersonas((java.awt.Frame) this.getOwner(), rootPaneCheckingEnabled, c, "tercerosDe");
        bp.setIdPersona(cliente.id_persona);
        bp.setVisible(true);
    }//GEN-LAST:event_VerTercerosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetallesClientes dialog = new DetallesClientes(new javax.swing.JFrame(), true, c, cliente);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboContadores;
    private javax.swing.JTextField FCP;
    private javax.swing.JTextField FCorreo;
    private javax.swing.JTextField FHonorarios;
    private javax.swing.JTextField FNombre;
    private javax.swing.JTextField FRFC;
    private javax.swing.JButton VerTerceros;
    private javax.swing.JButton cambiar;
    private javax.swing.JButton cambiar1;
    private javax.swing.JCheckBox checkCP;
    private javax.swing.JCheckBox checkContador;
    private javax.swing.JCheckBox checkCorreo;
    private javax.swing.JCheckBox checkHonorarios;
    private javax.swing.JCheckBox checkNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaRegimenes;
    private javax.swing.JButton regimenes;
    // End of variables declaration//GEN-END:variables


}
